### ISSUE TITLE
[Feature Request] Several plots in the same html

### ISSUE THREAD

**Issue by weatherwax** [pablrod/p5-Chart-Plotly#2]
It would be convenient to be able to draw several plots in the same html file. For example, with 
`data => [\@data1, \@data2]`

**Comment by pablrod** [comment]
Yes! But that syntax is already used for multiple traces in one plot.

What about something like this:
```perl
my $data1 = [1..5];
my $data2 = [map {rand 10} 1..20 ];
show_plot($data1, $data2);
```

**Comment by weatherwax** [comment]
You are right, I hadn't noticed.

**Comment by pablrod** [comment]
First try. Please see examples/multiple.pl (https://github.com/pablrod/p5-Chart-Plotly/commit/96340b5b40ba41b68392ed531f00aaf5af3a511c)

**Comment by weatherwax** [comment]
Great! Just what I was looking for.

**Comment by pablrod** [comment]
With the release of the version v0.009 we can draw multiple plots in the same html with [`show_plot`](https://github.com/pablrod/p5-Chart-Plotly#show_plot) and also get the html as a string with [`html_plot`](https://github.com/pablrod/p5-Chart-Plotly#html_plot).
