### ISSUE TITLE
Switch from JSON to JSON::MaybeXS?

### ISSUE THREAD

**Issue by iynehz** [pablrod/p5-Chart-Plotly#20]
@pablrod, do you think it fine to switch to JSON::MaybeXS? For one of my Chart::GGPlot example that has 50K data points this could save about 1sec. If you think it fine I will create a PR.

**Comment by pablrod** [comment]
It's fine for me!

I've read the differences between JSON and JSON::MaybeXS and I see no problem!
Also I like the speed improvement!! :wink:

**Comment by iynehz** [comment]
I just realized why JSON was slow on my host was because that I did not have JSON::XS and JSON would fallback to JSON::PP in this case. Now with JSON::XS installed there is no performance difference compared to JSON::MaybeXS which uses Cpanel::JSON::XS. So I think for now there is not the need to switch to JSON::MaybeXS. We might revisit this if in future we find limitations in JSON/JSON::XS.

**Comment by pablrod** [comment]
Ok! Then It's better not to switch to JSON::MaybeXS.
