### ISSUE TITLE
support plotly responsive:true

### ISSUE THREAD

**Issue by iynehz** [pablrod/p5-Chart-Plotly#27]
This is some feature in plotly>=1.41. It allows plot auto-resizable when browser window resizes. 

See
https://github.com/plotly/plotly.js/issues/106
https://plot.ly/javascript/configuration-options/#making-a-responsive-chart

**Comment by pablrod** [comment]
Great! I missed that so I'm going to include support for that ASAP!

**Comment by pablrod** [comment]
I've made a first implementation and I've set responsive:true as the default. I think it's a good option

BTW I've seen (https://plot.ly/javascript/plotlyjs-function-reference/#plotlyplot) that I'm using a deprecated function so I'm creating a new issue to change `Plotly.plot` by `Plotly.react`. #29

**Comment by pablrod** [comment]
> I've made a first implementation and I've set responsive:true as the default. I think it's a good option

I have reconsidered this option and it is better not to use it by default

**Comment by pablrod** [comment]
@stphnlyd I've released a new version [0.027](https://github.com/pablrod/p5-Chart-Plotly/releases/tag/v0.027)  (Already indexed in [MetaCPAN](https://metacpan.org/release/PABLROD/Chart-Plotly-0.027)) with config support, for making a chart responsive and all the [configuration options](https://plot.ly/javascript/configuration-options/)!

Please don't hesitate to ask for anything you miss in Chart::Plotly! Thank you!
