### ISSUE TITLE
Support kaleido

### ISSUE THREAD

**Issue by iynehz** [pablrod/p5-Chart-Plotly#54]
@pablrod I recently created Chart::Kaleido https://github.com/stphnlyd/perl5-Chart-Kaleido . IMHO we can add a Chart::Plotly::Image that has a function similar to python plotly's write_image https://github.com/plotly/plotly.py/blob/25a77f3f7e320f1e8238751354fd707b058a0177/packages/python/plotly/plotly/io/_kaleido.py#L137, which gets a "engine" parameter which defaults to kaleido but user can also use orca. If you think it fine I can create a PR.

**Comment by pablrod** [comment]
Yes! It would be great to support Kaleido!

I agree with you. Adding `Chart::Plotly::Image` would be the best option. Please, create a PR.

If I can help you, just let me know.

Thanks @stphnlyd

**Comment by pablrod** [comment]
Released version [0.040](https://github.com/pablrod/p5-Chart-Plotly/releases/tag/v0.040)!
