### ISSUE TITLE
Ship a local copy of plotly.js

### ISSUE THREAD

**Issue by iynehz** [pablrod/p5-Chart-Plotly#9]
It can remove the need of accessing plotly's site. Both the R and python plotly library can do it.

**Comment by pablrod** [comment]
Good point! This is going to be useful!! 

Thank you for the issue!

**Comment by pablrod** [comment]
I've done a first implementation. Plotly cdn is used by default, but there are two other options:

* `module_dist` uses the module distribution shared directory (almost always different on each computer)
* `embed` the Plotly.min.js code is in the html (this is useful for standalone html reports)

The examples [distribution_js.pl](https://github.com/pablrod/p5-Chart-Plotly/blob/7b59a28bf8a21c34fd4be1dd86a5607b80e1c70d/examples/distribution_js.pl) and [embed.pl](https://github.com/pablrod/p5-Chart-Plotly/blob/7b59a28bf8a21c34fd4be1dd86a5607b80e1c70d/examples/embed_js.pl) show how to use this.

As always, every comment is welcome!

**Comment by iynehz** [comment]
Thanks! I will see if I can try it this weekend. But I think your design is good enough for now. 

As a side node, R's plotly library generates a htmlwidget object which uses the installed plotly.min.js, and when you save this object to a file, say foo.html, htmlwidget would create a foo_files directory and copy the js dependencies there.

**Comment by pablrod** [comment]
Good! Thank you!!

Well I left that option unimplemented mostly because the lack of _htmlwidget_ object in Perl (btw something useful for a Perlish [Dash](https://github.com/plotly/dash) ) but it's easy to implement so I'll try to have it available for the weekend!

**Comment by pablrod** [comment]
As we still don't have (as far as I know) a working implementation of _htmlwidget_ and without this, I'm not going to implement the option of creating the foo_file directory with the js dependencies.
Maybe we can add this in the future, but for now the options for shipping a local copy of plotly.js are enough.
